name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
      PIP_DISABLE_PIP_VERSION_CHECK: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps (tests only)
        run: |
          python -m pip install --upgrade pip
          pip install pytest numpy matplotlib pyyaml

      - name: Show env (debug)
        run: |
          python -V
          pip -V
          pytest --version
          ls -la
          ls -la tests

      - name: Run tests
        run: |
          pytest -q tests
