name: CI

on:
  pull_request:   # <-- push'ı kaldırdık

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install pytest numpy matplotlib pyyaml
      - name: Sanity: list tests
        run: |
          python - << 'PY'
          import glob, sys
          files = glob.glob('tests/*.py')
          print("tests found:", files)
          sys.exit(0 if files else 1)
          PY
      - name: Run unit tests
        run: |
          pytest -q tests
