name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg  # matplotlib'ı headless çalıştır
      PIP_DISABLE_PIP_VERSION_CHECK: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps (tests only)
        run: |
          python -m pip install --upgrade pip
          pip install pytest numpy matplotlib pyyaml

      # İstersen ruff da koşabiliriz; ama önce testleri stabilize edelim.
      # - name: Lint (ruff)
      #   run: |
      #     pip install ruff
      #     ruff check .

      - name: Run tests
        run: |
          pytest -q tests
