name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONPATH: ${{ github.workspace }}   # proje kökünü import yoluna ekle

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          pip install pytest numpy matplotlib pyyaml

      - name: Show env (quick debug)
        run: |
          python -V
          pip -V
          python - <<'PY'
          import os, sys, glob
          print("cwd:", os.getcwd())
          print("sys.path[:3]:", sys.path[:3])
          print("tests:", glob.glob('tests/*.py'))
          PY

      - name: Run unit tests
        run: |
          pytest -q tests || code=$?
          # pytest exit code 5 = "no tests collected" -> yeşil say
          if [ "${code:-0}" = "5" ]; then
            echo "::notice::No tests collected; marking success"
            exit 0
          fi
          exit "${code:-0}"
